---
title: "TITLE"
author: "Daniel E. Weeks"
date: "`r format(Sys.time(), '%B %d, %Y, %R')`"
header-includes:
- \usepackage{pdflscape}
- \newcommand{\blandscape}{\begin{landscape}}
- \newcommand{\elandscape}{\end{landscape}}
- \usepackage{fvextra}
- \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
output:
  pdf_document:
    toc: true
    number_sections: true
    toc_depth: 3
  html_document:
    df_print: paged
    toc: true
    number_sections: true
    toc_depth: '3'
    code_folding: show
#   md_extensions: +raw_attribute
---

```{r,echo=FALSE,message=FALSE,warning=FALSE}
require(knitr)
# Set so that long lines in R will be wrapped:
opts_chunk$set(tidy.opts=list(width.cutoff=80),tidy=TRUE)
```

```{r,echo=FALSE}
# In the event of a crash, save the working space on exit:
save_all <- function() {
  save.image("recover.RData")
}
options(error = save_all)
```

```{r, echo=FALSE}
# Turn on chunk timing
# Using code from
# https://bookdown.org/yihui/rmarkdown-cookbook/time-chunk.html

all_times <- list()  # store the time for each chunk
knitr::knit_hooks$set(time_it = local({
  now <- NULL
  function(before, options) {
    if (before) {
      now <<- Sys.time()
    } else {
      res <- difftime(Sys.time(), now)
      all_times[[options$label]] <<- res
    }
  }
}))
```

```{r, echo=FALSE}
knitr::opts_chunk$set(time_it = TRUE)
```

------

```{r start_time, echo=FALSE,comment=NA}
start_time <- Sys.time()
```

**Start time:** `r Sys.time()`

# Load Libraries

```{r load_libraries,message=FALSE}
library(tidyverse)
library(tidylog)
library(pander)
```

# Input directory and files 

```{r getwd}
# Print the working directory
getwd()
```
The input files used in this analysis are ... and can be found in ... 

To draw graphs containing large numbers of points, use these R chunk options:

```
{r, dpi=600, dev='png'}
```

# Analysis

```{=latex}
For this raw LaTeX chunk to work, need to turn on this option in the YAML header
above:
%   md_extensions: +raw_attribute
```

# Time Stamp

```{r TimeStampNow}
TimeStampNow <- gsub(":","",gsub(" ","_",format(Sys.time())))
TimeStampNow
```


# Session Information

```{r ChunkTimes, echo=FALSE}
list1 <- lapply(all_times, function(x) {as.numeric(x, units="secs")})
as.data.frame(list1) %>% t() %>% as.data.frame() -> df
df$`Chunk Name` <- row.names(df)
df$Seconds <- df$V1
row.names(df) <- NULL
df$Minutes <- df$Seconds/60
df$Hours <- df$Minutes/60
df <- df %>% dplyr::select(`Chunk Name`, Seconds, Minutes, Hours)
pander(df, caption="Chunk Timing")
```

```{r, echo=FALSE}
end_time <- Sys.time()
tdiff <- end_time - start_time
tdiffstr <- paste0(round(tdiff,3)," ",attr(tdiff,"units"))

mem_use <- gc()
MaxMemUseCol <- which(colnames(mem_use)=="max used") + 1
max_mem_use <- mem_use[1,MaxMemUseCol] + mem_use[2,MaxMemUseCol]
```

------------------ 

**End time:** `r Sys.time()`      
**Elapsed time:** `r tdiffstr`         
**Memory used:** `r sprintf("%.1f", max_mem_use)` MB or `r sprintf("%.1f", max_mem_use/1024)` GB

              

```{r}
sessionInfo()
```

